Fix sorting of advanced attribute list
keepassxreboot/keepassxc pull request #10091
Opened 2023-12-10 18:10 UTC by marco-langer

Sort advanced attribute list using locale aware sort.

Fixes #6175

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
1. Add an entry to a database
2. Go to "Edit entry" -> "Advanced"
3. Add some additional attributes via the "Add" button. E.g.: "Test1", "Test12", "Test2"
4. The additional attributes should be sorted now as "Test1", "Test2", "Test12"

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

2025-01-12 17:14 UTC, droidmonkey requested changes

2025-01-12 17:14 UTC, droidmonkey commented on src/gui/entry/EntryAttributesModel.cpp
> +        QCollator collator;
Need to instantiste QCollator once, it's a very expensive (time wise) class to create

2025-01-13 19:01 UTC, marco-langer commented on src/gui/entry/EntryAttributesModel.cpp
> +        QCollator collator;
Thanks for the feedback!

Considering that this PR is from 2023 and I haven't worked on it since then: Do you think it is worth it to continue with this PR? I remember that I opened the PR, however some CI pipeline failed and I put it back to draft mode. Haven't had a look into it since then.

I could try to rebase the branch onto dev and implement your feedback if you think the PR is worth it, otherwise I could withdraw it given the long inactivity time.

2025-01-13 20:20 UTC, droidmonkey commented on src/gui/entry/EntryAttributesModel.cpp
> +        QCollator collator;
I can handle the rebase.

2025-02-01 16:59 UTC, droidmonkey approved these changes

2025-02-01 16:59 UTC, merged