Force clear clipboard on Wayland
keepassxreboot/keepassxc pull request #10624
Opened 2024-04-24 11:42 UTC by droidmonkey

* Fixes #4498
* Fixes #8721

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

2024-04-25 12:22 UTC, droidmonkey commented
Welp the attempted AppImage fix _does not work_. Trying to call xdg-open directly didn't work.

2024-04-28 16:55 UTC, phoerious requested changes

2024-04-28 16:55 UTC, phoerious commented on src/gui/DatabaseWidget.cpp
> +            QProcess::execute(QString("xdg-open %1").arg(url.toString(QUrl::FullyEncoded)));
```suggestion
            QProcess::execute("xdg-open", {url.toString(QUrl::FullyEncoded)});
```

2024-04-28 16:55 UTC, phoerious commented on src/gui/MainWindow.cpp
> +    QProcess::execute(QString("xdg-open %1").arg(url));
Same.

2024-04-29 07:02 UTC, phoerious approved these changes

2024-04-29 12:49 UTC, merged