Hide the menubar when menus lose focus (if toggled off)
keepassxreboot/keepassxc pull request #11355
Opened 2024-10-12 20:18 UTC by droidmonkey

* Fixes #10768
* Also fix menubar toggling not working if Qt version is less than 5.15

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Tested manually

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

2024-10-12 20:41 UTC, varjolintu requested changes
This doesn't work properly. If you follow these steps, you cannot get the menubar back until you've changed the option via Application Settings:

1. Disable the Show Menubar option from menu. Confirm that it works properly.
2. Enable the Show Menubar option from menu.
3. Menu bar goes hidden again. You cannot get it back even when pressing Alt. Is the timer still running? Or the options is not actually checked?
4. Go to Application Settings and change the value of Show Menubar. Everything works again.

2024-10-12 20:44 UTC, droidmonkey commented
Oops, forgot to guard the timer with the config setting

2024-10-12 20:51 UTC, droidmonkey commented
@varjolintu fixed

2024-10-13 04:54 UTC, varjolintu approved these changes

2024-10-13 14:05 UTC, droidmonkey commented
Cleaned up the code logic a little bit and reduced the timeout to 250ms. 1 second resulted in weird delays.

2024-10-16 08:54 UTC, xboxones1 commented
It works well, but I don't know how critical it is, hiding with Alt button sometimes works incorrectly. Instead of hiding the menu, the first menu item is opened. 
![keepassxc](https://github.com/user-attachments/assets/baf8e164-89c6-46d1-99f6-c673cbfbaa9e)

2024-10-16 12:08 UTC, varjolintu commented
Dunno if it's worth saving the last menu opened?

2024-10-16 12:12 UTC, droidmonkey commented
Pressing ALT in the situation shown in the video should hide the menu bar, will have to look into that.

2024-10-26 14:29 UTC, droidmonkey commented
> It works well, but I don't know how critical it is, hiding with Alt button sometimes works incorrectly. Instead of hiding the menu, the first menu item is opened. 

Fixed it with a cooldown timer that ignores the ALT key for 250ms. This is because on Windows pressing ALT de-selects the active menu which causes the timer to hide the toolbar and then releasing ALT causes the toolbar to re-appear. So ignoring that key release ensures the toolbar stays hidden.

2024-10-26 15:06 UTC, merged