introduce a security option to enable copy on doubleclick (Issue  #1575)
keepassxreboot/keepassxc pull request #6433
Opened 2021-04-21 05:04 UTC by xvallspl

Introduces a checkbox in the security section of the preferences to enable the
current feature (now disabled by default) of copying DatabaseView entries
columns, such as username and password, on double click. Addresses issue #1575.

- [x]  Implement new checkbox
- [ ] Think of a better descriptive text 

- [ ] Figure out how to test it

- [ ] Document the new functionality in the User Guide

## Screenshots

<img width="783" alt="Screenshot 2021-04-21 at 06 45 18" src="https://user-images.githubusercontent.com/867299/115499163-3ccbf080-a26f-11eb-8531-7220a8937a2a.png">

## Testing strategy

Figuring this out

## Type of change
- ✅ New feature (change that adds functionality)
- ✅ Breaking change (causes existing functionality to change)
- ✅ Documentation (non-code change)

2021-04-21 10:37 UTC, droidmonkey requested changes

2021-04-21 10:37 UTC, droidmonkey commented on src/gui/DatabaseWidget.cpp
> +        case EntryModel::Totp:
I think we can always allow this one. The column is just an icon and it is very common to copy/paste totp values since they are ephemeral.

2021-04-21 10:37 UTC, droidmonkey commented on src/gui/DatabaseWidget.cpp
> +        case EntryModel::Url:
This should always be allowed as well since it opens the URL

2021-04-21 10:37 UTC, droidmonkey commented on src/gui/DatabaseWidget.cpp
> +        case EntryModel::ParentGroup:
This should be always enabled as well

2021-04-21 16:26 UTC, xvallspl commented
Any ideas on how to test this?

2021-04-21 17:17 UTC, droidmonkey commented
Just test manually, this is low impact and automated tests involve timing and other crap that regularly breaks testing in CI

2021-04-21 17:30 UTC, xvallspl commented
Then this one should be ready to go

2021-04-21 18:52 UTC, droidmonkey requested changes

2021-04-21 18:52 UTC, droidmonkey commented on src/gui/DatabaseWidget.cpp
> +    if ((column == EntryModel::Username || column == EntryModel::Password)
This is an awkward way to handle this. I'd rather test the setting within the switch statement for username and password. If enabled copy the data, if not open for editing.

2021-04-22 10:08 UTC, droidmonkey approved these changes
Elegant!

2021-04-23 03:13 UTC, droidmonkey commented
Need to run code format

2021-04-23 04:28 UTC, xvallspl commented
Sorry, I guess my clangd plugin is misconfigured

2021-04-23 14:53 UTC, phoerious commented
Could also just be a different version. Make sure you have the latest.

2021-04-24 15:35 UTC, merged