Add command line option to lock open databases
keepassxreboot/keepassxc pull request #6511
Opened 2021-05-11 17:13 UTC by wundrweapon

Closes/Fixes #6126

This adds a command line option `--lock` which locks all open databases in the running instance. This also makes some minor changes to the codebase (e.g. changing `bool sendFileNamesToRunningInstance(const QStringList& fileNames)` to `bool sendToRunningInstance(quint32 id, const QStringList& fileNames)` for more flexibility in future), as well as some comments to explain what appears to be going on in otherwise-confusing code. Some of these comments are TODOs, particularly one that urges the use of an enum going forward per droidmonkey's idea.

## Screenshots
![--lock option in the --help print](https://i.imgur.com/lLSWreR.png)

## Testing strategy
I loaded up one real database and one dummy database, then ran `keepassxc --lock`. As expected, both locked.

## Type of change
- ✅ New feature (change that adds functionality)
- ✅ Documentation (non-code change)

2021-05-13 03:06 UTC, droidmonkey requested changes

2021-05-13 03:06 UTC, droidmonkey commented on src/gui/Application.cpp
> +bool Application::sendToRunningInstance(quint32 id, const QStringList& fileNames)
You are abusing this function to do two completely different things depending on what is passed to the parameters. You should instead split the function:
`Application::sendFilenamesToInstance(filenames)`
`Application::sendLockToInstance()`

2021-05-13 03:06 UTC, droidmonkey commented on src/gui/Application.cpp
> +    if (id == 1) out << fileNames; //send file names to be opened, if that is the command. TODO: make this not suck
This will be deleted when you split the function, but all if statements need to use brackets.
```
if (id == 1) {
    ...
}
```

2021-05-13 03:06 UTC, droidmonkey commented on src/gui/Application.cpp
> + * Right now nullptr fileNames is sent as long as it is not empty. This is not sustainable; the sent data (if any)
this comment is not true, you are not sending nullptr you are sending an empty list.

2021-05-13 20:34 UTC, wundrweapon commented
That commit _should_ resolve your comments

2021-05-15 13:04 UTC, droidmonkey approved these changes

2021-05-15 13:48 UTC, merged