FdoSecrets: implement unlock before search
keepassxreboot/keepassxc pull request #6943
Opened 2021-09-24 21:01 UTC by Aetf

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )
Resolves #4443. While at it, also fixes #6942

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
![image](https://user-images.githubusercontent.com/1519759/134737921-a5366183-6044-42d6-8603-cf136e97a0d2.png)

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Added unit test also tested manually

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)

2021-09-24 21:28 UTC, Aetf commented
While haven't tested it yet, but I realize using a nested event loop for the blocking call isn't the best approach. What if another dbus call happens while KPXC sits in the nested loop? If the other call is for unrelated parts, it is probably fine because there won't be any other nesting.
But what if the other call also results in unlocking the same database?

Actually, that's a problem in general: what will happen while one database is being unlocked asynchronously, and another client requests to unlock the same database.

I need to think more about this. The solution is probably to remember database unlocking is in progress, and for any new requests, submit to the old prompt signal rather than create a new unlock dialog.

Changing to WIP for now.

2021-09-25 05:09 UTC, Aetf commented
Ready for review (or probably wait after #6915 so the history is cleaner) @droidmonkey

2021-09-25 05:24 UTC, michaelk83 commented
So you're going with just an internal blocking prompt, without all the `IsLocked` / `InteractiveAuthorizationRequired` stuff?

2021-09-25 18:48 UTC, Aetf commented
> So you're going with just an internal blocking prompt, without all the `IsLocked` / `InteractiveAuthorizationRequired` stuff?

Yes. I view this as a workaround to increase compatibility.

The proper fix should be done in the spec, either returning `InteractiveAuthorizationRequired` error, or returning a prompt object just like other methods. IMHO returning a prompt object is better and consistent with the rest of the spec, though.

2021-10-01 22:38 UTC, droidmonkey commented
Rebased and squashed. Ready for review @Aetf ?

2021-10-01 22:46 UTC, Aetf commented
Somehow I can't reproduce the test failure `TestGuiFdoSecrets::testServiceUnlockItems` locally. But let me try to reproduce in the CI docker environment.

2021-10-02 02:31 UTC, Aetf commented
Found the root cause of test failure. Ready to review. @droidmonkey

2021-10-09 18:40 UTC, droidmonkey requested changes

2021-10-09 18:40 UTC, droidmonkey commented on src/gui/DatabaseWidget.h
> +    size_t deleteEntries(QList<Entry*> entries, bool confirm = true);
I don't like re-using this function call from within FDO Secrets plugin. Perhaps the GuiTools deleteEntriesResolvedReferences should be called directly from the FDO Secrets. Then you don't need to modify the signature of the DatabaseWidgets.

2021-10-09 18:40 UTC, droidmonkey commented on src/gui/entry/EditEntryWidget.cpp
> +    , m_historyWidget(new QWidget(this))
Why was this code changed? Parenting is handled in the addPage call.

2021-10-09 19:03 UTC, Aetf commented on src/gui/entry/EditEntryWidget.cpp
> +    , m_historyWidget(new QWidget(this))
This reduces some LSAN noise when the unit test fails and `addPage` isn't called. Not a big deal outside of tests. I can drop this if you don't like it.

2021-10-09 19:11 UTC, Aetf commented on src/gui/DatabaseWidget.h
> +    size_t deleteEntries(QList<Entry*> entries, bool confirm = true);
I thought about this. My only concern is the additional handling of selection and previewView in DatabaseWidgets. What if the user is viewing the exposed group while some backend clients delete some entries?

2021-10-09 19:17 UTC, Aetf commented on src/gui/DatabaseWidget.h
> +    size_t deleteEntries(QList<Entry*> entries, bool confirm = true);
(Or probably entryView should be fixed to react to entry delete signal and update selection and preview itself?)

2021-10-09 20:28 UTC, droidmonkey commented on src/gui/entry/EditEntryWidget.cpp
> +    , m_historyWidget(new QWidget(this))
Just unrelated to the FDO code, you can keep it since it doesn't change anything.

2021-10-09 20:29 UTC, droidmonkey commented on src/gui/DatabaseWidget.h
> +    size_t deleteEntries(QList<Entry*> entries, bool confirm = true);
I think the latter is the better solution. The GUI should "repair itself" automatically when the backend data changes. Can fix this in a different PR.

2021-10-12 14:48 UTC, Aetf commented on src/gui/DatabaseWidget.h
> +    size_t deleteEntries(QList<Entry*> entries, bool confirm = true);
Updated to directly use GuiTools. Will create a separate PR fixing the DatabaseWidget.

2021-10-12 22:26 UTC, Aetf commented
@droidmonkey updated this per comments. I also created #7041 to clean up deleteEntries.

2021-10-13 02:44 UTC, droidmonkey approved these changes

2021-10-17 02:50 UTC, merged