Add db statistic output to CLI db-info command.
keepassxreboot/keepassxc pull request #7032
Opened 2021-10-09 17:44 UTC by glysbaysb

Fixes #6920

# Allow the user to also see the statistics while using the cli

# Code modifications.

A small refactor, moving an internal class to it's own file and using it from one additional place

## Testing strategy
I have amended an existing unit test

## Type of change
- ✅ New feature (change that adds functionality)

2021-10-10 21:46 UTC, louib requested changes
I love this PR! I added a few comments, but it's looking good overall.

2021-10-10 21:46 UTC, louib commented on src/cli/Info.cpp
> +    out << QObject::tr("Database name") << ": " << database->metadata()->name() << endl;
@glysbaysb the database name and database description were already part of the output, no need to print them twice.

2021-10-10 21:46 UTC, louib commented on src/core/DatabaseStats.h
> +    void gatherStats(const QList<Group*>& groups)
@glysbaysb I think the functions should be defined in a `src/core/DatabaseStats.cpp` file. This is pretty much what we do everywhere else.

2021-10-10 21:46 UTC, louib commented on src/core/DatabaseStats.h
> +                    if (pwd.size() < 8) {
@glysbaysb I know you only copied the code from `ReportsWidgetStatistics.cpp`, but I think it would be worth it to extract the `8` and `25` hardcoded values to constants in the `PasswordHealth` module. Something like `PasswordHealth::Length::Short` and `PasswordHealth::Length::Long`

2021-10-25 22:12 UTC, louib approved these changes
good job! Not sure why the MacOS tests are failing though...

2021-11-05 03:06 UTC, droidmonkey commented on tests/TestCli.cpp
> +        QByteArray("Location: /tmp/testcli"))); // name is randomly generated so just test the path
Just remove the path portion of this check, it is not a portable test, the path is different on each platform. Alternatively inject the path of the current test database file into the expected output.

2021-12-09 04:41 UTC, merged