Feature/remote database support
keepassxreboot/keepassxc pull request #7222
Opened 2021-12-12 22:29 UTC by t-h-e

As discussed here: https://github.com/keepassxreboot/keepassxc/issues/1775#issuecomment-983056115

This change provides the ability to sync a database with a remote database with the help of `scp`. (Fixes #1775)
The `RemoteSettingsDialog` works similar to `DatabaseSettingsDialog` and can be extended in the future to store previous settings and load them again.
Although currently `scp` is supported, the implementation is extensible to include further programs in the future to download and upload .kdbx files to sync with them.

Feedback is very welcome as this would be my first contribution to KeePassXC

## Testing strategy
Place a second database on a separate server that is accesible via `ssh` and have `scp` installed and in your PATH variable.
The second database can include keys and/or groups that the current database does not.
The new "Remote Sync ..." feature is available in the UI next to "Merge From Database...".

Regarding unit tests: Help is very welcome as I am uncertain how to mock the QProcess. I expect the rest to work similarly to `TestGui::testMergeDatabase`

## Type of change
- ✅ New feature (change that adds functionality)

2022-01-06 19:04 UTC, t-h-e commented
@droidmonkey I think this PR is ready for review. As mentioned in the discussion of the issue, I'm not a C++ developer, so feedback is very welcome 😃

2022-01-06 19:08 UTC, droidmonkey commented
Excellent, will review when I get the chance

2022-02-09 04:31 UTC, hifi commented
I'll add a note that `scp` is considered harmful and this should probably use `sftp` instead.

2022-02-22 20:14 UTC, t-h-e commented
> I'll add a note that `scp` is considered harmful and this should probably use `sftp` instead.

While [OpenSSH recommends](https://www.openssh.com/txt/release-8.0) to use modern protocols like `sftp` or `rsync`, in the near future `scp` will be [running with SFTP protocol](https://www.openssh.com/txt/release-8.8). Since version 8.7, `scp` can already be used with [SFTP protocol with the switch `-s`](https://www.openssh.com/txt/release-8.7).
The benefit of `scp` over `sftp` is that a single file upload can be done with a single command, which makes it easier to use.

I have changes for using `rsync` and `curl` nearly finished, but I would prefer to at least get some feedback first to know if this feature is heading in the right direction. More protocols can easily be added.

2022-02-23 05:07 UTC, hifi commented
AFAIK you can use a single command with sftp if you batch it through stdin. That's without any temporary files.

I have high personal interest in this PR so I'll be testing this as well and providing feedback once I get around to.

2022-02-23 11:06 UTC, hifi commented
I took a quick look, it's promising but maybe it's not being utilized to its fullest potential with hardcoded commands.

I'm thinking sync over SSH is an advanced user feature so what if this would be simplified to "Sync Command" and instead provide a generic mechanism to run a command that can be templated with the database path and possibly other options? We'd only check that the return code of the command is a success and if not possibly show the code and stdout+stderr for debugging.

We could still provide presets for scp, sftp etc. for convenience. This allows the user to write script that takes the arguments from KeePassXC and does whatever with them.

2022-02-26 21:33 UTC, KFDCompiled commented
I've contributed to the #1775 bounty and am excited to test this PR!

2022-03-01 19:02 UTC, t-h-e commented
@hifi using templating and running arbitrary commands is a great idea. It is way more flexible. Running the sync command after unlocking as shown in [your comment](https://github.com/keepassxreboot/keepassxc/issues/1775#issuecomment-1051001958) would definitely be a convenient feature. 👍 
You seem to have way more keepassxc experience. I am not sure if I should even proceed with my PR then 😆

2022-09-01 08:24 UTC, t-h-e commented
@droidmonkey @phoerious Any chance to get a review for this PR? It is nearly 10 months old now 😞

2022-09-01 08:30 UTC, phoerious commented
Yes, sorry for the delay. But first, could you please rebase it to the latest develop HEAD and fix the conflicts?

2022-09-01 09:00 UTC, t-h-e commented
Done 😃

2022-09-09 05:44 UTC, t-h-e commented
PR is rebased and conflicts are resolved. The build works mostly. The only issue seems to be that `TestGui::testSaveBackup` fails sometimes, but I cannot reproduce the behaviour locally.
Do you have any idea why this test might fail? It does not seem to fail for all build configurations.

2022-09-10 17:36 UTC, droidmonkey commented
I'll give this a review soon

2022-11-06 20:28 UTC, t-h-e commented
Hi, I added now the possibility to run any commend to download or upload a keepass file for syncing.
For some reason my test fails on the CI. I can execute the test on a windows and linux machine without issues though 🤷

2023-01-12 03:10 UTC, HexF commented
I've tested this out a little and come across a few quirks:
1. When doing a remote sync, the UI entirely locks up whilst downloading and uploading the database, giving no indication to the user as to what is going on.
2. While using the anyCommand feature with `rclone`, I managed to copy my Keepass database into a directory named with `{TEMP_DIRECTORY}`, rather than copying the file which produced no error up until I fill all the credentials in and get a "cannot open file" error.
3. When synchronizing the exact same database I am required to select my key file and enter my password again, this is a little inconvenient. I would much prefer the derived key from my currently open database be tried first before asking for my password and key file again.

2023-01-12 19:33 UTC, t-h-e commented
@HexF Thanks so much for testing and your feedback. 😊 
Some comments from my side:
1. Yes, that should be handled better, but is further down the priority list. Although I think that can be fixed quickly
2. That is weird. Do you have more input on this error how to reproduce it?
3. This annoys me as well. The code is inspired by the merging feature, where this is also necessary. I have to check if there is a more convinient solution.
4. Hmm, that I understand, but what if you want to sync to a different location afterwards. Maybe the menu can have an option "sync with previous settings" or offer a drop down with the last options. This is probably connected to 5.
5. Not all functionality is implemented yet.
6. True, I might just use a dash.

On a side note: I had some time the last weeks and added an option to also be able to open a remote database. I will update the PR as soon as I have some tests and cleaned the code.
Afterwards I will work on your suggestions. Thanks again.

2023-01-13 00:42 UTC, HexF commented
> That is weird. Do you have more input on this error how to reproduce it?

I imagine using a command such as `mkdir {TEMP_DATABASE}` should do it.

2023-01-31 22:06 UTC, t-h-e commented
I have added a "remote open dialog" to allow people to open remote databases with KeePassXC directly. This uses a lot of the functionality that I added previously.
Next step is to address some of the issues mentioned by @HexF

2023-02-06 07:41 UTC, HexF commented
Looking at the remote open, I don't see any hook for a save to upload/merge the database with the remote one. Could this be added?

2023-02-06 19:17 UTC, t-h-e commented
Sure that is easy enough.
I still need to figure out what's wrong with the tests on TeamCity. Locally (windows and linux), all tests run fine.

2023-02-10 14:50 UTC, mazunki commented
I haven't tried out this feature yet, but I hope that when the feature is implemented, there would be a hook to automatically push passwords to ${DEFAULT_REMOTE} whenever an update is done, and some mechanism to automatically pull password each ${RESYNC_INTERVAL} seconds. 

Is this feasible to implement?

2023-02-21 21:27 UTC, t-h-e commented
Update:
* Remote sync does not require password input if the same key/password is used. If a different key/password is used, the user will be prompted to input as before
* Download/upload run concurrently and do not block GUI anymore
* Added more info in the status bar during remote sync
* Values (command, url, port etc.) used in the remote sync are stored in the config and are not lost anymore when restarting KeepassXC
* Braces in the filename have been removed

2023-02-25 20:00 UTC, t-h-e commented
@droidmonkey Can you help me figure out what is wrong with my tests? Locally everything works fine. I ran the tests on Windows 10 and Manjaro Linux. Nevertheless the pipeline fails consistently. As I cannot reproduce the failing tests, it is difficult to fix them. Can you reproduce the failing tests or have a look what is going on?

Also, which version of QT is the pipeline using? I had to remove the usage of `QUuid::WithoutBraces` as the symbol was not recognized. See commit https://github.com/keepassxreboot/keepassxc/pull/7222/commits/51ddff19efdf1ce9c17badf8e5a384bca2369144. This symbol was already introduced in [version 5.11](https://doc.qt.io/qt-6/quuid.html#StringFormat-enum)

2023-02-25 20:07 UTC, droidmonkey commented
You have a crash that is occurring on one of the download tests, specifically with the scp download

2023-03-29 21:16 UTC, t-h-e commented
Update:

- No more `scp` specific widget. All commands have to be defined in the same way (Previously named `anyCommand`)
- Multiple remote settings can be defined with a name
- Upload without sync is supported
- Menu offers the option to directly sync with a previously defined remote setting. The saved setting needs the "Add to Menu checked"

Remote sync settings:
![image](https://user-images.githubusercontent.com/999552/228668813-89a5d9d0-d982-496b-9e45-c98f902562e2.png)

Remote sync menu
![image](https://user-images.githubusercontent.com/999552/228668912-d29779d5-046f-480a-85ef-216d1cec4043.png)

@HexF Can you give it another look?
@mazunki For now I have decided against an automated sync mechanism. Mainly to get the current version out of the door. But yes, it can be done at some point.

@droidmonkey @phoerious Can one of you give the PR a review? I think the feature has matured since the first implementation 😃

2023-03-29 22:05 UTC, droidmonkey commented
This looks great! Will give a thorough review when I can, currently absolutely swamped

2023-03-30 10:16 UTC, HexF commented
I'll give this a test later tonight

2023-03-31 06:41 UTC, HexF commented
I'm a big fan of the changes made, especially the ability to save my upload/download scripts - makes all the difference.
Not having to enter my password & select my keyfile is also great.

Remote Opening appears to be a bit broken - it opens for me and pulls the latest database, but when I save & sync, the database doesn't update on the remote.

Remote opening also indicates the database path as `/tmp/RemoteDatabase-.....` in the open dialog, which isn't very user friendly:
![image](https://user-images.githubusercontent.com/11236933/229041166-1de52dee-aaff-4519-9339-9f5fd2856534.png)

My Recent Databases is also filled with these databases:
![image](https://user-images.githubusercontent.com/11236933/229041233-4d2830fa-44f5-4442-be45-b312d8fde5f7.png)

Ideally, these should say something along the lines of "NextCloud Remote Database" (replacing NextCloud with the name of the remote config)

When I remotely open I get a dialog like this after hitting OK with no feedback as to what is happening:
![image](https://user-images.githubusercontent.com/11236933/229041580-a3ec1adf-f343-49f0-a362-2373d951fffe.png)


I'm not sure that syncing is working at all for me, my commands are
```sh
# Download
rclone --config /run/secrets/thobson_rclone_config copyto nextcloud:Passwords.kdbx {TEMP_DATABASE}
# Upload
rclone --config /run/secrets/thobson_rclone_config copyto {TEMP_DATABASE} nextcloud:Passwords.kdbx
```
These commands to upload a file to nextcloud.

If I create an entry "Test Entry":
![image](https://user-images.githubusercontent.com/11236933/229042630-5f612ec6-5e10-4b39-81de-d8aaa80a8e8f.png)

then click Remote Sync -> NextCloud, I confirm on the bottom right action bar I see "Uploading"

I then download the file from NextCloud, opening it in Keepass.
I note the entry does not exist.

I am on commit 74220fa622989550ba54115a297d9bf45b5d35a1

2023-03-31 18:33 UTC, t-h-e commented
@HexF Thanks for the detailed feedback.

- Bug: The uploaded file in case of both databases having the same key, has not been saved. Thanks for finding this one 😃
  - In case the keys are different, it works, but probably only due to the automatic save setting
- I will add a progress bar to the dialog so that the user can see that something is happening
- I forgot about the "Recent databases". Yes that can be improved. I will have a look, but don't see it as major blocker.

2023-04-03 21:55 UTC, t-h-e commented
- Bug fixed: Save source and destination database before uploading
- Remote databases are not added to recent databases
    - in the future it may make sense to add the remote settings recently used, but that is more complicated
    - using a name without UUID will lead to issues if opening a remote database and trying to sync it. Therefore I opted for suppressing remote database file paths for now
- Added status bar to remote file dialog

2023-04-04 23:38 UTC, HexF commented
I can confirm the bug has been fixed.

One thing I would like to see is being able to automatically sync my database when I lock it.

On the tabs up here, it would be nice to differentiate which one is open locally, and which one is open from a remote. At this stage its impossible to tell.
![image](https://user-images.githubusercontent.com/11236933/229944242-0baa25b9-3c9a-49c5-8c28-c596ea5265b3.png)

When I want to unlock the database, I am presented with the same `RemoteDatabase-` path, which in my mind should say something more like `Remotely Opened Database from NextCloud`

![image](https://user-images.githubusercontent.com/11236933/229944418-c7bc154d-4067-4363-a98c-2fb47edf00cc.png)

The documentation when setting up remote sources could be documented a bit better, especially the Command field, which doesn't indicate that you can use `{TEMP_DATABASE}` placeholder in it at all.

Other than those few things, I'm perfectly happy with the UX

2023-04-17 21:07 UTC, t-h-e commented
- added "[Remote]" in tab name
![image](https://user-images.githubusercontent.com/999552/232610109-4a1a9dbb-adb7-483f-9776-4277ba9f2a62.png)

- added another example for the remote dialog that `TEMP_DATABASE` can also be used in the command
![image](https://user-images.githubusercontent.com/999552/232610240-6fa6b01e-77e3-495e-b649-4b7fd803e250.png)

- remote databases are not saved in `LastDatabases`, `LastActiveDatabase` and `LastOpenedDatabases` as the paths saved may lead to non-existend temporary files.
- rebased the PR

As the feature has matured quite a bit and IMHO is ready to be reviewed/merged, I will refrain from further feature changes unless related to a review or bug fixes.

I'm looking forward to a review 😃 
(The failing MacOS test is also failing in other PRs)

2023-05-22 13:18 UTC, dvilker commented
Just fantasy out loud.

It could be done so that the program could "open" files like *.kdbx.sh.
And used it like this:
To read the file I ran mydb.kdbx.sh open and read the output.
And to write the file, I would run mydb.kdbx.sh save and write the file to the input.

Or read the first line #!... and run that. How shell does it.

And no UI would have to do.

2023-05-22 17:19 UTC, droidmonkey commented
You can use an external utility such as Watchman to do this. We will never execute external scripts from keepassxc.

2023-06-05 14:26 UTC, KFDCompiled commented
This works.  I started the bounty for #1775 and I think this satisfies all requirements.  Any objections to awarding bounty to @t-h-e ?

2023-06-08 10:26 UTC, t-h-e commented
@KFDCompiled I have submitted this PR to issuehunt. But maybe you should ask for objections in the [issue](https://github.com/keepassxreboot/keepassxc/issues/1775) as not as many might have subscribed for updates to the PR.

2023-06-08 20:55 UTC, droidmonkey commented
All I ask before I review and merge this... please go once over again an cleanup any temporary or messy code and add documentation.

2023-06-11 14:02 UTC, t-h-e commented
@droidmonkey I had another glance at the code and did a minor cleanup, otherwise the code looks well-structured to me. 
The PR has also been rebased again. Let me know if there is anything specific that needs to be changed or is blocking the merge from your point of view.

2023-06-11 14:09 UTC, droidmonkey commented
Ran through real quick, you are missing some `tr(...)` wrappers around text strings for gui display. You also need to add newlines to end of several files. Also get the documentation written up please.

2023-06-11 14:26 UTC, t-h-e commented
With documentation you mean a PR to https://github.com/keepassxreboot/keepassxc-org/blob/main/content/docs/KeePassXC_UserGuide.html ?
I have added the `tr(...)` wrappers and newlines.

2023-06-11 17:27 UTC, droidmonkey commented
No, either add a section on remote database operations to the below topic or create a new topic and link it in.

https://github.com/keepassxreboot/keepassxc/blob/develop/docs/topics/DatabaseOperations.adoc

These files compile into the html documentation

2023-06-11 18:12 UTC, t-h-e commented
Thanks, will do.
One more question. What tool did you use to annotate the screenshots with numbers, arrows etc.? I'm asking so that my screenshots have the same look

2023-06-11 18:23 UTC, droidmonkey commented
SnagIt, I can do screenshots if you like

2023-06-22 20:05 UTC, t-h-e commented
@droidmonkey I have added documentation for the remote database support. If you could replace the provisional screenshots with ones made with SnagIt so that they look more consistent and nicer that would be great. You may also want to update `docs/images/welcome_screen.png` as there is now a fourth button.

Let me know if there is anything else I need to add.

2023-06-22 20:10 UTC, droidmonkey commented
Awesome will review

2023-06-23 19:24 UTC, droidmonkey commented
OK here is a functionality review:

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/cba707ec-6801-44fe-ba49-2d4f258aff6b)

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/88c5afa7-0dde-48e6-bed9-f23323904bd8)

![image](https://github.com/keepassxreboot/keepassxc/assets/2809491/63fb008a-4599-403f-95b7-9fb83123c8f1)

2023-07-02 18:41 UTC, t-h-e commented
Thanks for the functional review.

I think most changes can easily be done.

Regarding the storage of the sync settings. They can be stored in `Database::pubicCustomData`, as each database may have their own sync settings. This would also allow to use placeholders as suggested here: https://github.com/keepassxreboot/keepassxc/issues/1775#issuecomment-1051001958
But I'm not sure this works well for "Open from remote" use case. If a remote database is opened, it is saved in a temporary folder. So unless the user saves it in another directory as well, it may be gone soon. If I would use "Open from remote", I may want to open the same remote database again the next time I open KeepassXC. Therefore, the settings need to be stored someplace other than within the database, so that as a user I can open the remote database again quickly without having to type the command each time.

Do you have a suggestion how to accommodate the "Open from remote" use case within KeepassXC? The only option I see is to store it within the config.

2023-07-02 20:43 UTC, droidmonkey commented
No, do not store in `publicCustomData` use the `customData`

2023-07-05 15:47 UTC, QORTEC commented
Why not give the option of caching the remote database (save in a "cache" folder)?
- If the database is cached the credentials to sync can be retrieved from there. 
- If the database is not cached (/tmp) then we can assume that the user doesn't want the database easily accessible form the computer.


This would also enable us to give the option to open the cached database if the remote database is not accessible.
This would probably be read only, since merge/conflict logic required is definitely beyond the scope of this pull request.

2023-09-06 09:10 UTC, darktohka commented
What is the status on this pull request? It would be nice to have remote database access.

2023-09-06 19:38 UTC, t-h-e commented
I hope to have some time next month to finish up the suggestions.
I haven't had much time or sleep (👶) the last couple of months

2023-09-07 15:26 UTC, HexF commented
Not sure if this is a bit late in the development cycle for this PR, or if I should just wait for this to be merged and PR it myself:

I would love to be able to use secrets from within the database in the commands.
I could see this being useful for syncing to WebDAV services such as NextCloud which require username/password or username/access token, which I already have stored in the database.

I was thinking similar to `{TEMP_DATABASE}` there can be a template such as `{54093383-9e73-42e6-b634-87fab8dfab81:password}` where `54093383-9e73-42e6-b634-87fab8dfab81` is the UUID of an entry in the database and `password` is the name of some attribute associated with the entry.

There are probably some security implications with this, such as the command being placed in publicly writable areas, which could lead to entry leakage by knowing a uuid of a record.
I'm sure there are ways to iron this out into a secure but user-friendly feature, such as requiring approval to access records in a similar way to FDO secrets and the browser extension.

Again, if you want to skip implementing this - no sweat, I'll get it done myself :)

2023-10-12 19:14 UTC, t-h-e commented
Finally I had a little bit of time.

- Remote settings are now part of database settings (see first screenshot)
- Settings are stored within `customData`
- Name cannot be an empty string anymore
- Open remote dialog has been reduced to the essential (see second screenshot)
  - Settings used for opening are _not_ stored anymore

![image](https://github.com/keepassxreboot/keepassxc/assets/999552/d6cdbef3-cc8e-402b-b30d-7df030176451)
![image](https://github.com/keepassxreboot/keepassxc/assets/999552/f08b31e1-86f8-482d-9f16-23e5259832d1)

@droidmonkey Can you have another look?

Documentation still needs to be updated.

MacOS tests currently break as I'm trying to open a menu to trigger the aboutToShow signal of QMenu. Freaking Mac 😡 
Not sure how to solve this or if I disable the remote tests.

2023-10-12 19:14 UTC, t-h-e commented
@HexF sounds great. In  a follow up PR 😉

2023-10-12 20:44 UTC, droidmonkey commented
Awesome will queue up another review.

2023-11-05 20:08 UTC, t-h-e commented
Updated remote sync documentation

I have also borrowed a Mac to check on the test issue. I setup the Mac and ran the tests. Everything worked. I rebased my changes and the pipeline now runs successfully for Mac as well. Seems that the issue was actually with the pipeline.
Now the pipeline fails in an unrelated test for Ubuntu. Not sure what is going on, but I guess that there are some flakey tests the break in the pipeline once in a while.

2023-11-22 19:43 UTC, t-h-e commented
Hi, @droidmonkey just pinging you regarding the review 😃

2023-12-23 23:04 UTC, droidmonkey commented
I made a bunch of edits to this PR I need to push, please don't rebase or merge anything for now

2023-12-28 17:19 UTC, t-h-e commented
Sure. Let me know if you need anything 😃

2024-02-12 13:41 UTC, tw-atroehrsm commented
meow? dont stop halfway through pls 🙏

2024-02-12 13:52 UTC, droidmonkey commented
I am done with my refactoring, testing the functionality now. There are a few areas that concern me with this capability in general, but it works!

2024-02-13 07:57 UTC, HexF commented
Ideally in the documentation we should spell out that the exit code is responsible for determining success of a transfer.
Thus we should suggest people use `scp` over `sftp` and other application which require no stdin interaction.

2024-02-13 10:37 UTC, droidmonkey commented
I have an idea, basically check that the temp database file actually exists and its size is not 0 bytes. Otherwise return an error that shows the stdout/stderr from the command.

2024-02-24 14:23 UTC, t-h-e reviewed
Thanks for the refactoring.
The UI looks way better now, I love the new icon ❤️ and of course thanks for the code improvements.

I tested the changes on Windows and I'm running into the issue that the sync does not work anymore due to the following error:
```
QObject: Cannot create children for a parent that is in a different thread.
(Parent is RemoteHandler(0x1dfe3fa4720), parent's thread is QThread(0x1dfdc72c8d0), current thread is QThreadPoolThread(0x1dfe0e7d080)
```
I remember that I had this issue during development at some point in time as well, but cannot remember how I solved it.

I left a few comments regarding the code changes. The main issue is that the tests are not compiling at the moment, but I guess you are still working on the PR, right?

2024-02-24 14:23 UTC, t-h-e commented on src/gui/MainWindow.cpp
> +    connect(m_ui->tabWidget, SIGNAL(updateSyncProgress(int, QString)), this, SLOT(updateProgressBar(int, QString)));
This signal does not exist anymore.
`No such signal DatabaseTabWidget::updateSyncProgress(int, QString)`

2024-02-24 14:23 UTC, t-h-e commented on src/gui/remote/RemoteProcess.cpp
> +QString RemoteProcess::readError()
Good idea to have the error available

2024-02-24 14:23 UTC, t-h-e commented on src/gui/remote/RemoteHandler.h
> +    void sync(const QSharedPointer<Database>& db, RemoteParams* params);
`sync` is not implemented.

2024-02-24 14:23 UTC, t-h-e commented on src/gui/remote/RemoteHandler.h
> +    static void setRemoteProcessFunc(std::function<QScopedPointer<RemoteProcess>(QObject*)> func);
`setRemoteProcessFunc` is not implemented anymore.
As the comment suggests, it was only used for testing, to be able to mock `RemoteProcess` as I did not want to start a real process during testing.

The method seems to be still used in test, which is one of the reasons why building the tests fails.

2024-02-24 14:23 UTC, t-h-e commented on tests/gui/TestGui.cpp
> +            new MockRemoteProcess(parent, QString(KEEPASSX_TEST_DATA_DIR).append("/SyncDatabase.kdbx"), sourceToSync));
`MockRemoteProcess` only takes a single argument after refactoring. This is why building tests fails at the moment.

2024-02-24 14:40 UTC, droidmonkey commented
I need to push my latest, I'm slowly chipping away at the refactoring.

2024-02-24 14:56 UTC, droidmonkey commented
Take another look now

2024-02-24 15:07 UTC, droidmonkey commented
You can see my latest here: https://github.com/droidmonkey/keepassxc/tree/feature/remote-database-support

2024-02-24 22:12 UTC, t-h-e reviewed
The architecture of the code is way nicer than before. Thanks for cleaning up the code 👍 

The sync works again with the newest changes 😃

The "Open Remote Database" still has a bug though, but I assume you know it already.
After clicking OK, with any command, the progress bar appears, but the dialog buttons are still clickable.
Nothing happens after clicking OK. Neither if the download command should work or fail.

2024-02-24 22:12 UTC, t-h-e commented on src/gui/DatabaseWidget.cpp
> +bool DatabaseWidget::syncWithDatabase(const QSharedPointer<Database>& otherDb, QString& error)
👍 
It makes sense to only pass in `otherDb` rather than passing in two databases, as one can be accessed via `m_db`.
Also using `error` as reference rather than showing a message in this method is cleaner architecture

2024-02-24 22:12 UTC, t-h-e commented on src/gui/DatabaseWidget.cpp
> +    Merger secondMerge(otherDb.data(), m_db.data());
IMHO, I liked the previous naming better `mergerToRemote` and `mergerFromRemote`, rather than `firstMerge` and `secondMerge` as the new names to not convey the meaning why this merge is necessary.

2024-02-24 22:12 UTC, t-h-e commented on src/gui/DatabaseWidget.cpp
> +        RemoteHandler::RemoteResult result;
I'm getting an error here, as the variable in line 1050 has the same name is therefore shadowed

2024-02-24 22:12 UTC, t-h-e commented on src/gui/MainWindow.cpp
> +    connect(m_ui->tabWidget, SIGNAL(updateSyncProgress(int, QString)), this, SLOT(updateProgressBar(int, QString)));
This error still occurs

2024-02-24 22:12 UTC, t-h-e commented on tests/gui/TestGui.cpp
> +    QSignalSpy dbSyncSpy(m_dbWidget.data(), &DatabaseWidget::databaseSyncedWith);
`databaseSyncCompleted` instead of `databaseSyncedWith`?
Same in test `testRemoteSyncDatabaseRequiresPassword`

2024-02-24 22:12 UTC, t-h-e commented on tests/gui/TestGui.cpp
> +            new MockRemoteProcess(parent, QString(KEEPASSX_TEST_DATA_DIR).append("/SyncDatabase.kdbx"), sourceToSync));
`MockRemoteProcess` only takes two arguments now.

2024-03-19 11:12 UTC, tburny commented
Please continue working on this, I am eagerly waiting to move away from KeePass2 on Ubuntu and this is the only feature that prevents me from doing so.

Please let everyone know if you need any help. I'd be more  than happy even to sponsor this project once this feature works well.

2024-03-19 11:27 UTC, droidmonkey commented
Now that 2.7.7 is out I will resume this work

2024-04-04 20:27 UTC, KaKi87 commented
Hi,
How is it going ?
Thanks

2024-04-16 08:33 UTC, roelbroersma commented
@droidmonkey  Keep up the good work! 👍 👍  I know it can be hard and bureaucratic to pass the whole PR process, but once it's past,.. you did it!  Come on, the last few inches..!

2024-04-24 11:19 UTC, t-h-e commented
Hi @droidmonkey, is there anything I can help with to get this PR over the finish line?

2024-04-24 11:46 UTC, droidmonkey commented
I lost my focus on this one, can you just look through the code and clean it up. I just pushed my latest commit without testing it, looks like I still need to remove some legacy artifacts from all the other code changes we have been doing.

```
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:255:36: error: out-of-line definition of 'importFile' does not match any declaration in 'DatabaseTabWidget'
[00:13:14] :	 [Step 2/4] DatabaseWidget* DatabaseTabWidget::importFile()
[00:13:14] :	 [Step 2/4]                                    ^~~~~~~~~~
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:343:25: error: out-of-line definition of 'importKeePass1Database' does not match any declaration in 'DatabaseTabWidget'
[00:13:14] :	 [Step 2/4] void DatabaseTabWidget::importKeePass1Database()
[00:13:14] :	 [Step 2/4]                         ^~~~~~~~~~~~~~~~~~~~~~
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:357:15: error: no member named 'switchToImportKeepass1' in 'DatabaseWidget'
[00:13:14] :	 [Step 2/4]     dbWidget->switchToImportKeepass1(fileName);
[00:13:14] :	 [Step 2/4]     ~~~~~~~~  ^
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:360:25: error: out-of-line definition of 'importOpVaultDatabase' does not match any declaration in 'DatabaseTabWidget'
[00:13:14] :	 [Step 2/4] void DatabaseTabWidget::importOpVaultDatabase()
[00:13:14] :	 [Step 2/4]                         ^~~~~~~~~~~~~~~~~~~~~
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:378:15: error: no member named 'switchToImportOpVault' in 'DatabaseWidget'
[00:13:14] :	 [Step 2/4]     dbWidget->switchToImportOpVault(fileName);
[00:13:14] :	 [Step 2/4]     ~~~~~~~~  ^
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:676:9: error: use of undeclared identifier 'db'
[00:13:14] :	 [Step 2/4]     if (db->isRemoteDatabase()) {
[00:13:14] :	 [Step 2/4]         ^
[00:13:14] :	 [Step 2/4] /Users/KPXC/buildAgent/work/c401303cba1b4098/src/gui/DatabaseTabWidget.cpp:681:9: error: use of undeclared identifier 'db'
[00:13:14] :	 [Step 2/4]     if (db->isModified()) {
[00:13:14] :	 [Step 2/4]         ^
[00:13:14] :	 [Step 2/4] 7 errors generated.
```

2024-05-01 20:33 UTC, t-h-e commented
@droidmonkey If I remember correctly, you suggested to integrate opening a remote database into the import wizard, right?
Here is a mockup:
![image](https://github.com/keepassxreboot/keepassxc/assets/999552/1d46de32-1ed9-43e8-b47c-4b3f1fc8dcd3)

I have added the "Command" and "Input" fields to download the remote database file.
I'm not sure about with options should be available for the "Import Into" section. I have added an option "Temporary Database" in the mockup, which would open the database, but not store it anywhere, except in the `tmp` folder of your OS, which will get deleted at some point. Another possible option would be to specify a save location, like "Save Database to:"

Do you have any suggestions?

2024-05-01 20:41 UTC, droidmonkey commented
Hey that's nifty, I don't recall making that suggestion though. New database and existing database seem accurate to me. Temporary database doesn't make much sense if I'm going through all this trouble to specify the remote settings. Basically you want to land the user with an "in memory" database that needs to be saved prior to close which will force the file choice dialog. That is what New Database generally does, but in this case you wouldn't need to show the new database workflow.

2024-05-02 07:53 UTC, michaelk83 commented
> integrate opening a remote database into the import wizard

The mockup looks overwhelming at first glance. What do you think about moving the command and input fields to the next wizard page? So you'd have the normal import wizard on the 1st page, then if you selected remote database, you're basically given a view of the remote access settings page, populated with your default settings. Then you can review your settings and adjust them just for the current import.

And I think this might be best to leave to a separate PR.

2024-05-04 18:41 UTC, t-h-e commented
@michaelk83 I would refrain from adding another page in the wizard as it can get annoying to click through many pages in a wizard. The fields for downloading the database are only shown in case "Remote Database" is selected anyway. But I agree with the suggestion of having the import/open of a remote database in a separate PR. I should have done that in the first place.

@droidmonkey The code is compiling again.
I have added the functionality again that a remote database with a different key can be unlocked and synced.
The tests are working again (hopefully the CI agrees)
The progress bar that I added at some point seems to be gone. The progress bar displayed if the application is currently downloading, syncing or uploading so that the user is aware the something is going on rather than thinking the application is not responding. Was the progress bar removed by accident in one of the refactorings or was it on purpose? In the first case, I can add it again.

Otherwise, I think the PR is ready for review.

PS: I have left out the import wizard for now and will link a follow up branch/PR in the next couple of days that adds support for opening/importing a remote database. Is that alright?

2024-05-04 19:45 UTC, droidmonkey commented
Yup I agree, thank you for getting this back on track.

2024-05-07 21:50 UTC, t-h-e commented
@droidmonkey I have solved some merge conflicts and added the progress bar again.

Additionally, here is the PR for the support of opening/importing a remote database: https://github.com/t-h-e/keepassxc/pull/1
Currently the "open remote database" PR is only in my fork as it is based on this open PR to be merged first.

Let me know if you have any feedback, so that we can get this PR merged.

2024-05-27 13:04 UTC, winnieXY commented
Any news on that?

2024-06-04 13:14 UTC, t-h-e commented
@droidmonkey Is there any chance to get a review any time soon?

2024-06-09 14:49 UTC, droidmonkey requested changes
General Notes:
* Locking a database while attempting to sync keeps the UI disabled. Should cancel the sync immediately or wait until it is finished. I prefer the latter.
* There needs to be a "Test" button on the download sync settings page. Its a frustrating workflow to set the settings, save, OK, Database -> Remote Sync -> [Sync Name]. Obviously cannot test upload since that would cause data loss. Download can just run through the sequence and discard any resulting file.
* I cannot get this to work on Windows for whatever reason. It used to work but not any more. I suspect we may need to use this function to manipulate the underlying CreateProcess call: https://doc.qt.io/qt-5/qprocess.html#CreateProcessArgumentModifier-typedef

2024-06-09 14:49 UTC, droidmonkey commented on src/core/AsyncTask.h
> +#include <utility>
This doesn't appear to be used

2024-06-09 14:49 UTC, droidmonkey commented on src/core/AsyncTask.h
> +    template <typename FunctionObject> void runAndWaitForFinished(FunctionObject func)
I don't prefer this to be added. You should use the non event loop blocking function that does a callback when done.

2024-06-09 14:49 UTC, droidmonkey commented on src/core/Config.h
> +        Remote_Program_Settings,
This doesn't follow naming patterns

2024-06-09 14:49 UTC, droidmonkey commented on src/gui/DatabaseWidget.cpp
> +    Merger secondMerge(otherDb.data(), m_db.data());
I'm going to reuse this function for "sync with database" which is chosen from a file dialog. Nothing about this function is specific to a remote database since that aspect is handled from a different function.

2024-06-09 14:49 UTC, droidmonkey commented on src/core/CustomData.cpp
> +const QString CustomData::RemoteProgramSettings = QStringLiteral("Remote_Program_Settings");
I really want to name this `KPXC_REMOTE_SYNC_SETTINGS`, we should do this now but it'll break anyone who used this PR before the change.

2024-06-09 14:49 UTC, droidmonkey commented on src/core/Database.cpp
> +    if (emitSignal && !m_isRemoteDatabase) {
I really don't like this. We should always emit signals when state changes. You can (and should) choose to ignore them as the receiver based on your criteria. So if we want to ignore the fact that a database is "clean" if it is remote, then we should do that at the tab widget or database widget level. 

However this variable is also named wrong. In reality this is `m_isTemporaryDatabase` based on its use.

2024-06-09 14:49 UTC, droidmonkey commented on src/gui/DatabaseOpenDialog.cpp
> +    }
This is a weak association between the unlock dialog and the database being "remote". Technically we are marking this because the database is temporary in nature. This should be done at the point this distinction is made and not the open dialog. The open dialog should be left "neutral" to the type of database it is opening.

Unfortunately our unlocking logic is very complicated. It goes something like this:
DatabaseOpenDialog -> dialogFinished -> DatabaseWidget -> unlockDatabase -> syncUnlockedDatabase -> ....

DatabaseOpenDialog -> dialogFinished -> DatabaseTabWidget -> handleDatabaseUnlockDialogFinished

I'm not really sure what to do here but the complexity is a problem.

2024-06-09 14:49 UTC, droidmonkey commented on src/gui/DatabaseWidget.cpp
> +    }
Not sure if this holds true based on the usage of this variable. The old database being "remote" doesn't mean the new database is "remote" (or temporary?).

2024-06-09 14:55 UTC, droidmonkey commented
Pushing some initial feedback

2024-06-10 14:11 UTC, t-h-e commented
- ad "Locking a database": The menu bar and toolbar get disabled now during syncing. This helps avoid issues with all the other functionality available in the menu and toolbar as well.
- added a "Test" button for testing the download
- ad Windows: I'm using Windows 11 Pro 23H2 and everything works fine.

2024-06-10 14:11 UTC, t-h-e commented on src/core/CustomData.cpp
> +const QString CustomData::RemoteProgramSettings = QStringLiteral("Remote_Program_Settings");
Renamed

2024-06-10 14:12 UTC, t-h-e commented on src/core/Database.cpp
> +    if (emitSignal && !m_isRemoteDatabase) {
True. I removed the condition here. I don't think it is needed anymore anyway.
Also renamed the variable and corresponding methods.

2024-06-10 14:14 UTC, t-h-e commented on src/gui/DatabaseWidget.cpp
> +    }
True. I'm not sure anymore why I needed to add this. I removed this piece of code and will recheck it, before creating a PR for opening remote databases (https://github.com/t-h-e/keepassxc/pull/1)

2024-06-10 14:16 UTC, droidmonkey commented
I think my problems are with sftp, using password to unlock ssh key doesn't work.

2024-06-10 14:17 UTC, t-h-e commented on src/gui/DatabaseOpenDialog.cpp
> +    }
This complexity really took me some time to understand. I haven't found a better way to handle this 😔

2024-06-10 14:21 UTC, t-h-e commented
> I think my problems are with sftp, using password to unlock ssh key doesn't work.

Yes, that does not work. I run into the same issue in the beginning

2024-06-10 14:48 UTC, droidmonkey commented
Let's note that in the documentation. Workaround is to load the key to ssh-agent using the SSH Agent plugin.

2024-06-10 18:06 UTC, t-h-e commented
I have added a comment in the documentation.
All review comments have been addressed. Thanks for reviewing :smiley: 
Let me know if everything looks good now.

2024-06-13 02:18 UTC, droidmonkey commented
OK this is ready to merge once CI finishes! Great work. I added a check for changes in the remote settings page so you don't lose work by accident. Also some general cleanup.

2024-06-13 02:19 UTC, droidmonkey approved these changes

2024-06-13 10:23 UTC, merged

2024-06-25 18:47 UTC, varjolintu commented on src/gui/DatabaseWidget.cpp
> +    if (!params->downloadCommand.isEmpty()) {
Even if I have configured both Upload and Download commands, even the Upload command goes inside this function every time and fails. What am I doing wrong?

2024-08-21 14:38 UTC, KaKi87 commented
Hi,
Would it be possible to have a beta build for this ?
Thanks

2024-08-21 15:18 UTC, droidmonkey commented
Https://snapshot.keepassxc.org

2024-08-21 15:22 UTC, KaKi87 commented
That's nightly, not beta :sweat_smile:

2024-08-21 17:00 UTC, droidmonkey commented
That is our beta...

2024-08-21 18:33 UTC, KaKi87 commented
Well, I was hoping for a build that contains everything stable + remote databases support in addition, so that other experimental things wouldn't potentially add bugs to it. :/

2024-08-21 18:34 UTC, segln commented
Then how about just waiting for the next stable build

2024-08-21 18:40 UTC, KaKi87 commented
This PR is almost 3 years old, the milestone is only 32% complete containing many other posts that are years old, the latest minor version increment was done 4 years ago, all signs indicating that this PR will not be released in a stable build anytime soon...

2024-08-21 18:52 UTC, droidmonkey commented
2.7.9, the stable version, is 95% the same as a snapshot build off develop branch. Just use a snapshot and don't think too hard about it. Trust me you'll be OK.

2024-08-21 19:41 UTC, KaKi87 commented
What's with the very worrying warning message then ? The threat of loosing passwords is a big deal.

2024-08-21 20:21 UTC, droidmonkey commented
We are toning that down, its just to keep people from using non-final builds in production.

2024-08-23 13:32 UTC, Maasea commented
I tried the beta version and implemented data synchronization for webdav using the curl command, which is easy to use. 

But the data synchronization is manual, is it possible to add a switch to automatically trigger remote synchronization for data changes, and to automatically pull remote files for updates every time the database is unlocked.

2024-08-23 14:42 UTC, KaKi87 commented
> its just to keep people from using non-final builds in production

But that's what I would be doing 😅

2024-08-23 14:52 UTC, droidmonkey commented
@Maasea that can be built in, maybe on a periodic basis versus every save to avoid locking up the interface.

2024-11-12 14:30 UTC, alexp303 commented
Any idea when will the sync be included in the stable release?

2024-11-12 14:50 UTC, droidmonkey commented
This still needs a bit of trim work for UX, but you can use it now in our snapshot builds. They are rather stable, every change is well vetted.

2024-11-24 12:31 UTC, wschlich commented
> I tried the beta version and implemented data synchronization for webdav using the curl command, which is easy to use.
> 
> But the data synchronization is manual, is it possible to add a switch to automatically trigger remote synchronization for data changes, and to automatically pull remote files for updates every time the database is unlocked.

Can you please share your WebDAV sync implementation for KeePassXC using curl? Thank you!

2024-11-24 13:55 UTC, wschlich commented
@droidmonkey The current solution using remote sync settings per database stored inside the database itself (I guess in the KDBX headers?) is an interesting idea, I successfully tried using it with WebDAV and 2 cURL commands.

But how should it work using AutoOpen for other WebDAV DBs as supported by both (!) KeePass and KeePass2Android?

Right now, I have a main KDBX file on a WebDAV server.
I can just open the HTTPS-URL using KeePass and KeePass2Android and specify I/O username + I/O password for WebDAV (these can be cached by both KeePass and KeePass2Android so I don't need to enter them every time when I open that main DB).

In that main KDBX file, there's an AutoOpen folder, containing entries for other KDBX databases on other WebDAV servers.
These entries have an HTTPS-URL as well as IocUserName + IocPassword String fields which magically allow KeePass to open these WebDAV DBs without needing any more information.

Something like this (plain easily handleable!) seems to be impossible with the current DB-internal remote sync solution of KeePassXC? :-(

2024-11-24 13:59 UTC, droidmonkey commented
That is not supported and likely won't be. For awareness, keepass and keepass2android use the .NET framework which has support for web dav natively. Qt does not have this support and we are not interested in adding a third party library to add it. 

You could maybe achieve this in keepassxc by mounting the webdav folder in your OS and pointing your auto open to the mounted folder.

2024-11-24 14:08 UTC, wschlich commented
@droidmonkey 

> That is not supported and likely won't be. For awareness, keepass and keepass2android use the .NET framework which has support for web dav natively. Qt does not have this support and we are not interested in adding a third party library to add it.

Too bad, as there's a library available: https://github.com/PikachuHy/QtWebDAV

> You could maybe achieve this in keepassxc by mounting the webdav folder in your OS and pointing your auto open to the mounted folder.

Not portable across KeePass and KeePass2Android :-(

What about this idea:

As you already store DB remote sync settings inside the KDBX, what about adding support for the exact same kind of settings per AutoOpen entry as well, using String Fields, just like KeePass + KeePass2Android do with IocUserName + IocPassword, while ignoring the AutoOpen HTTPS-URL, but just using it as a {TEMP_DATABASE}?

To me, my master copy is the WebDAV remote anyway and not any local temporary/cached copy (as KeePassXC now seems to handle it).

2024-11-24 14:10 UTC, droidmonkey commented
You can have as many auto open entries as you want and use IfDevice. https://keepassxc.org/docs/KeePassXC_UserGuide#_automatic_database_opening

2024-11-24 14:11 UTC, wschlich commented
@droidmonkey
I believe you're completely missing my point here. It's about automatically opening *remote* WebDAV DBs using AutoOpen entries.
Please, read my comments again :-)

2024-11-24 14:12 UTC, wschlich commented
@droidmonkey 
The current implementation of remote database support in KeePassXC kills my highly portable workflow with multiple WebDAV DBs (one master and several AutoOpen WebDAV DBs specified inside) across KeePass2Android and classic KeePass -- it's really sad as I'd *love* to switch to KeePassXC on my Linux box because of .NET woes with mono on Linux :-(

2024-11-24 14:14 UTC, droidmonkey commented
I'm not missing your point. I'm telling you we aren't adding more features to this aspect of the program.

2024-11-24 14:18 UTC, wschlich commented
Very sad to read this. Thanks anyway :-)

2025-04-25 09:45 UTC, mazunki commented
> This still needs a bit of trim work for UX, but you can use it now in our snapshot builds. They are rather stable, every change is well vetted. https://snapshot.keepassxc.org/

Forgive my confusion, but does this mean it will be included in the 2.8.0 release? I suspect there's no specific ETA for that yet?

2025-04-25 09:59 UTC, droidmonkey commented
Yes and no era right now

2025-04-26 15:03 UTC, kschmid commented
Just tried out the remote sync feature from the most recent snapshot. This looks cool. Together with curl, I was able to successfully set up WebDav transfer. I am only confused about two things. 
a) The way I understand it, there is no way to have the local file at a fixed position? This confuses me. When I am traveling and have no remote access, it would be better to be able to access the most recent version at a local point. 
b) it seems, the only time remote sync happens, is when explicitly called for. - While this is nice, it might be even less errorprone, if remote-sync would be connected to opening dbs and (auto-)saving them. 

I hope, I got everything right. I tried to locate a corresponding user guide version, but it seems, there is not yet relevant doc for this.

2025-04-26 15:19 UTC, droidmonkey commented
Your local file is wherever your kdbx file is stored. Sync pulls down a temporary remote copy, performs a merge with the open copy, then saves the result locally.

2025-04-26 16:27 UTC, kschmid commented
Thanks a lot for the clarification with the merging. This escaped me. Just tried it out: very nice. 
Then also the explicit sync is not as problematic. - Though would still prefer "automatic merging", but if this is the decision...
Took me time to understand that these settings are also encrypted, so passwords could be part of the commands (which would simplify a lot. Overall very nice feature; looking forward to general release! Thanks for the great work!

2025-04-26 17:33 UTC, droidmonkey commented
Thank you for the feedback, we should make these things clearer

2026-10-22 07:19 UTC, buhtz commented
Hi Folks,

great tool btw. I am using it on Debian and Windows syncing the database via nextCloud.

The 2.8.0 changelog is IMHO insufficient.

Please specify the "external tools" in the changelog and release notes. Reading the linked issues it seems to be `scp` only. So it should be singular "external tool" (without "s").

Best,
Christian

2026-11-04 17:51 UTC, serious-angel commented
Wonderful day! :sparkles: 

Thank you very much for the marvel... art you do!

This is a great addition, finally! And is crucial...
I've been always using custom scripts for it since donations and use of KeePassXC I like much and appreciate for it...

For at least 5 years, the main client I've been using for KeePass synchronization on all devices that have KeePass data is [Rclone](<https://rclone.org/>), and would definitely recommend it, sure.

I've been into shell scripting since the start of the century, too, and custom synchronization scripts written in lovely Bash v5 work like a charm on all platforms, including Termux on Android, but when I try using the script in this new feature, or try a few simple experiments even, I get similar to the following only:

```
Download failed with error: Command `rclone` did not finish in time. Process was killed.
```

```
Download failed with error: Command `/usr/bin/rclone` did not finish in time. Process was killed.
```

```
Download failed with error: Command `bash -xc 'exit 3'` exited with status code: 2
```

```
Download failed with error: Command `sh -c 'exit 3'` exited with status code: 2
```

...etc.

The build I use is Flatpak based, and I tried passing the scripts/executables through [Flatseal](<https://github.com/tchx84/Flatseal>), but no avail.

I would try stracing it to find the exact issue source, but... what if the feature would have more logging, verbosity, so to actually see the output or more detailed errors?

2026-11-04 19:54 UTC, t-h-e commented
@serious-angel 
I have tested `bash -xc 'exit 3'` and `sh -c 'exit 3'` and get the same result. That is because [QProcess::splitCommand()](https://doc.qt.io/qt-6/qprocess.html#splitCommand) only understands double quotes.

`bash -xc "exit 3"` actually returns
```
Download failed with error: Command `bash -xc "exit 3"` exited with status code: 3
```

For testing I put my default setup `sftp` into a shell script:
```
#!/usr/bin/env bash
set -euo pipefail

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <local-destination>" >&2
    exit 1
fi

sftp user@myserver <<EOF
get mypasswords.kdbx $1
exit
EOF
```
and called it via `/path/to/download-pws.sh {TEMP_DATABASE}`. This also resulted in 
```
Download failed with error: Command ``/path/to/download-pws.sh {TEMP_DATABASE}`` did not finish in time. Process was killed.
```
The reason was I forgot to make it executable `chmod +x`. The error message is unfortunately not helpful in this case, but it was weird that the command did definitely not run into a timeout as it immediately showed the error.

So I guess, if you see the error message immediately, the issue is with executing the script. If you actually run into a timeout (10 seconds by default), something blocks the script from continuing. In that case I would ask you to run the script outside KeePassXC to test.

More logging would definitely help. But as I'm already waiting quite some time for [three other PRs to be merged](https://github.com/keepassxreboot/keepassxc/pulls/t-h-e), I do not want to spend more time on new PRs