Add support for retrieving credentials when non-connected database is active
keepassxreboot/keepassxc pull request #7270
Opened 2022-01-08 13:57 UTC by varjolintu

Current implementation does not allow retrieving credentials from a connected database if a non-connected database is on the active tab. The behavior is changed so that if "Search for all databases" option is enabled, all connected databases are returned on `geyKey()` and the matching hash is returned, instead of just checking the current active database.

An extra parameter `associated` is added to the JSON for browser extension because `test-associate` now returns `true` even if the active database is not  connected. The new parameters allows a backwards compatible way to check if the active database is truly associated with the extension.

Browser side PR coming soon.

Fixes #7269.

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
Manually.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ✅ Bug fix (non-breaking change that fixes an issue)

2022-06-04 20:34 UTC, droidmonkey requested changes

2022-06-04 20:34 UTC, droidmonkey commented on src/browser/BrowserService.cpp
> +    }
Combine these two for loops, if the database is unlocked then do the key search. You are also re-using the result of `isAssociated` in this block which I think is not appropriate?

2022-06-04 20:35 UTC, droidmonkey commented
Did you end up making the browser-side PR for this feature?

2022-06-05 07:42 UTC, varjolintu commented
> Did you end up making the browser-side PR for this feature?

I actuall forgot to make a PR about it but the branch already exists. I'll double check that it works properly.

2022-10-12 07:46 UTC, varjolintu commented
I've fixed this branch, but I'll update the PR after #8489 is merged.

2023-02-19 10:07 UTC, varjolintu commented
I have a new implementation coming for this. Closing as out-of-date.

2023-02-19 10:07 UTC, closed without merging