test: add test for maximum history in database settings
keepassxreboot/keepassxc pull request #9176
Opened 2023-02-27 23:16 UTC by jNullj

Add a test to the TestGui::testDatabaseSettings function for the history maximum items and maximum size settings.
The test opens the database settings dialog, disables the history items and size settings, saves the changes, reopens the dialog, and then cancels without making any changes to load the default values.
The test ensures that the default values are loaded correctly.

This tests:
1. That the two settings show and present defaults as expected.
2. Disable in gui saves the right values
3. Changing values (while the setting is disabled)
4. Gui behavior when those settings are disabled

[NOTE]: # ( Describe your changes in detail, why is this change required? )
[NOTE]: # ( Explain large or complex code modifications. )
[NOTE]: # ( If it fixes an open issue, please add "Fixes #XXX" )

## Screenshots
[TIP]:  # ( Do not include screenshots of your actual database! )
Example for affecting coverage in one of the files
gui/dbsettings/DatabaseSettingsWidgetGeneral.cpp
Before:
![image](https://user-images.githubusercontent.com/15849761/221710307-c06db557-be6b-4a76-9fb6-19621c7e7e0a.png)
After:
![image](https://user-images.githubusercontent.com/15849761/221710378-e3aaf9d8-e721-4e37-9f04-a1b862217506.png)

## Testing strategy
[NOTE]: # ( Please describe in detail how you tested your changes. )
[TIP]:  # ( We expect new code to be covered by unit tests and documented with doc blocks! )
running all tests, i also added delays and run the script line by line in debug.

## Type of change
[NOTE]: # ( Please remove all lines which don't apply. )
- ❎ Bug fix (non-breaking change that fixes an issue)
- ✅ New feature (change that adds functionality)
- ❎ Breaking change (causes existing functionality to change)
- ❎ Refactor (significant modification to existing code)
- ❎ Documentation (non-code change)

2023-02-28 05:15 UTC, dmaslenko requested changes

2023-02-28 05:15 UTC, dmaslenko commented on tests/gui/TestGui.cpp
> +    QVERIFY(historyMaxItemsSpinBox->value() == Metadata::DefaultHistoryMaxItems);
To compare 2 values better to use `QCOMPARE`, it produces more detailed and clear output on fails.

2023-02-28 05:15 UTC, dmaslenko commented on tests/gui/TestGui.cpp
> +    // then open to disabled state in gui
`// then open to check the saved disabled state in gui`
`                 ^^^       ^^^`

2023-03-01 16:22 UTC, dmaslenko approved these changes

2023-03-05 21:36 UTC, jNullj commented
did a rebase to latest commit at develop

2023-03-10 15:21 UTC, jNullj commented
did a rebase to latest commit at develop

2023-04-27 21:56 UTC, jNullj commented
Did a rebase to latest commit at develop

2023-05-19 20:01 UTC, jNullj commented
Did a rebase to latest commit at develop

2023-05-29 20:30 UTC, jNullj commented
Just a rebase to latest commit

2023-07-04 12:43 UTC, droidmonkey approved these changes

2023-07-04 12:43 UTC, merged